assignments: []
  #- node: <node name from node list>
  #  namespace: <destination namespace>
  #  createOsoNetworkData: false
  #  assignmentType: metal3 / agent
  #  extraLabels: {}
  #  extraAnnotations: {}
  #  infraEnvName: <infraenv name, only used if type is agent>

nodes: []
  #<name>:
  #  labels:
  #  osoCtlplaneGw:
  #  osoCtlplaneVlan:
  #  osoCtlplaneIp:
  #  osoMgmtVlan:
  #  osoMgmtGw:
  #  osoMgmtIp:
  #  annotations:
  #  bootMac:
  #  bmc:
  #   url:
  #   externalSecret:
  #     vaultName:
  #     usernameKey:
  #     passwordKey:
  #  network:
  #    nmstateConfig:
  #    interfaceMap:
