cluster:
  importToHub: true
  useACM: true
  createGitopsManifestWorks: false
  createGitopsSyncSet: false
  name: dz-shiftstack-2
  gitOpsRepo: "https://github.com/marbindrakon/signal9-lab-gitops.git"
  baseDomain: lab.signal9.gg
  clusterImageSet: img4.18.30-x86-64-appsub
  controlPlaneCount: 3
  workerCount: 0
  apiVIP: "172.18.190.163"
  ingressVIP: "172.18.190.102"
  pullSecretVault: "ocp-pull-secret"
  trustedCAs: |
    -----BEGIN CERTIFICATE-----
    MIIFvTCCA6WgAwIBAgIUANmDgsLhX6Lt4jvplsha7SLdeiEwDQYJKoZIhvcNAQEL
    BQAwZjELMAkGA1UEBhMCVVMxETAPBgNVBAgMCEFya2Fuc2FzMQ8wDQYDVQQHDAZS
    b2dlcnMxFTATBgNVBAoMDFNpZ25hbDkgTGFiczEcMBoGA1UEAwwTU2lnbmFsOSBS
    U0EgUm9vdCBYMTAeFw0yNTAxMDIwNDI3NTZaFw00OTA4MjUwNDI3NTZaMGYxCzAJ
    BgNVBAYTAlVTMREwDwYDVQQIDAhBcmthbnNhczEPMA0GA1UEBwwGUm9nZXJzMRUw
    EwYDVQQKDAxTaWduYWw5IExhYnMxHDAaBgNVBAMME1NpZ25hbDkgUlNBIFJvb3Qg
    WDEwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDJwYKQ/EKn7LMKfLT2
    olW3DFtUnmsP9d82dY9ytjWWzJJdHV5q73y/nFF5k3xASx0lkIE0saeohcIrQ2xI
    xtdSWfoMhZQAQH0fE4FBYU/8/NvQ7rehS2bvobzX6KWQIYN/LaupUDEkN5r43AuP
    m3+4TvvJfBW3x/CY9jsegFIA1iQUupewujDFd9HDf//rVlzk084FS8kwGM5K8z9G
    RT5ltuBSt2jRhIw2ieEMv6TsL5RwthLJePzHy0pTwZ4NPpef8YG5K3LyVxnko14k
    W3tL7Z/xljwlKqNlyleBhszkmj1cXtnLOHcEHJizvKFwScuBwtvYaGRBFMPn03dJ
    vMs8oiydgz6nHCzxnJtmCajrK9qdD6+tGBsVmXz1WScmYxUD/4MOpTIpHjvSKzVf
    xW7nTKenQM8aUejZTyGqBxRzxjeQmiZhW+DYZCMtyHiLcBTTxHCn5oTaA9ZO57ED
    n/tXrAL9P5EP1iR4n7vHUPau6LrZ1TYTQHjpiiOHaZ3IZpp8C/HvtiSBMZWAA/TR
    vc+1I90UBU24yi2Ix4C8Ss8XDvmoVnBCLe6+i4r+jSGRLfOktxM/VrP3eZj7+x3V
    m86IXTPeDvELhQv6/+kcBLvcRCXiV0b2zEacI+DH/JZ3XGDaVDHd5eKhn9TBz/+X
    HMvo0lCTvdlH06olm2i6uPdyIwIDAQABo2MwYTAdBgNVHQ4EFgQUYQizalJ4rewL
    SKdhWDf7/l7EoFEwHwYDVR0jBBgwFoAUYQizalJ4rewLSKdhWDf7/l7EoFEwDwYD
    VR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYwDQYJKoZIhvcNAQELBQADggIB
    AMkIrpfZSckITsEqRWxxvA6gd2HIqOJzMHnR+wVkMI0pRkX0As2IenRCtyAp4fRr
    zAFSi625RJUA+/QBtRKIOeZ1iaFBttw6qoG14ABecqygZY0lCT6iYdH6H2xp4C4b
    gcBMXhhRrTfMXsEyRtDefCFSpb2IGtflcA5gQuTo0OiNJ8+uHNTXcvZ6J9D7LG9T
    KpF1/KD4VehFHBuLzZLoPl4U5u8qPtsi+3lZ+CusdxmhISJ2zyqPsCB/jiSBqnQK
    sjem+Yv/znoLESVGzNqeTuekgIHVWfpruHhAszezEnSq6QtyKYQAKuGx3Q33KAC5
    gAgtbRnuCL+lAPoA0YQPtxwdhuXRjVFp0122wMiTT5A78Z4sdUd58pAsgfdu86Mp
    pdHDUUZMa4vmVanp4ADEe7tlS1U56O6vi+80C0tUVJ1BJivgRIyWOUEBU/K06fK6
    TRh1y7t+d24wbwu5RkFSPSnSX+oiCd5hL4odJRJ7LBzqC81y79EB+d0o2t2QBK6z
    rw1K831Un7jlZbDuB+M/iO1tdE/o8Uy0uzKE7v331gE8g8xPUnWW8QBqkYEMW8Yd
    7vLPo6XXL2JkO19C3xDAikZkv4akWGQDK7DHJMTa1fgylKK7E8zgovWIOqOG3gkj
    8KD/USuDE+Rtc5Pj+FSltBRzNz7b3F7jUrburZ+JctBx
    -----END CERTIFICATE----- 

  sshKeyVault: "rhte-cluster-ssh-key"
  sshPubKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDgvctEXuDg84taMVkL+cD8ny5F6f0+mYsMfTYa48SdBhU9nwB/W4/7vmTMNASWf0urWSDl4YtzSrsca5I1v8VA1LLdqSWD/bFPlLNRtZ4wTKidk9uk1uP5JyeYUpLB31Sq5P7cyzKcd8OaHgDgzPSk0nZIcrcU/hdO/A0UcMGEFZ4fDuMAVhHdjto7k4rQbyAZtsdkfDbex14wiNNy4bHeQxECV644+GAPy7xXDUT4j/AF1ud7sXTq1hnlIc12FtaIQZ3WGX69Om3Qv5XJL3mdYafX721xEIdyX+U8obr+dc2E7TtLxcrHCb8Rqko6rvy8YLLPx+2Dj4ypuDZCmS/3vWQ50kEwRsWze20z835cJEodNS5wo0RanrrGgCGRMlMi9xNofBWnvpr7VCBXgywPN2JmfDwDcurBvJ++L8ednadGI7Xqp8Q17LIM9b8ag92GeZ86ycmaVJUKCb5DRScMsn6UCC9QBL2I9pP+GKDNzjGFTXga+WSU0vhE5Jsng1c="
  dnsServers: ['172.18.42.10','172.18.42.11']
provider:
  providerCredsVault: dzcloud-cloud-config
  providerCAs: |
    -----BEGIN CERTIFICATE-----
    MIIFvTCCA6WgAwIBAgIUANmDgsLhX6Lt4jvplsha7SLdeiEwDQYJKoZIhvcNAQEL
    BQAwZjELMAkGA1UEBhMCVVMxETAPBgNVBAgMCEFya2Fuc2FzMQ8wDQYDVQQHDAZS
    b2dlcnMxFTATBgNVBAoMDFNpZ25hbDkgTGFiczEcMBoGA1UEAwwTU2lnbmFsOSBS
    U0EgUm9vdCBYMTAeFw0yNTAxMDIwNDI3NTZaFw00OTA4MjUwNDI3NTZaMGYxCzAJ
    BgNVBAYTAlVTMREwDwYDVQQIDAhBcmthbnNhczEPMA0GA1UEBwwGUm9nZXJzMRUw
    EwYDVQQKDAxTaWduYWw5IExhYnMxHDAaBgNVBAMME1NpZ25hbDkgUlNBIFJvb3Qg
    WDEwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDJwYKQ/EKn7LMKfLT2
    olW3DFtUnmsP9d82dY9ytjWWzJJdHV5q73y/nFF5k3xASx0lkIE0saeohcIrQ2xI
    xtdSWfoMhZQAQH0fE4FBYU/8/NvQ7rehS2bvobzX6KWQIYN/LaupUDEkN5r43AuP
    m3+4TvvJfBW3x/CY9jsegFIA1iQUupewujDFd9HDf//rVlzk084FS8kwGM5K8z9G
    RT5ltuBSt2jRhIw2ieEMv6TsL5RwthLJePzHy0pTwZ4NPpef8YG5K3LyVxnko14k
    W3tL7Z/xljwlKqNlyleBhszkmj1cXtnLOHcEHJizvKFwScuBwtvYaGRBFMPn03dJ
    vMs8oiydgz6nHCzxnJtmCajrK9qdD6+tGBsVmXz1WScmYxUD/4MOpTIpHjvSKzVf
    xW7nTKenQM8aUejZTyGqBxRzxjeQmiZhW+DYZCMtyHiLcBTTxHCn5oTaA9ZO57ED
    n/tXrAL9P5EP1iR4n7vHUPau6LrZ1TYTQHjpiiOHaZ3IZpp8C/HvtiSBMZWAA/TR
    vc+1I90UBU24yi2Ix4C8Ss8XDvmoVnBCLe6+i4r+jSGRLfOktxM/VrP3eZj7+x3V
    m86IXTPeDvELhQv6/+kcBLvcRCXiV0b2zEacI+DH/JZ3XGDaVDHd5eKhn9TBz/+X
    HMvo0lCTvdlH06olm2i6uPdyIwIDAQABo2MwYTAdBgNVHQ4EFgQUYQizalJ4rewL
    SKdhWDf7/l7EoFEwHwYDVR0jBBgwFoAUYQizalJ4rewLSKdhWDf7/l7EoFEwDwYD
    VR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYwDQYJKoZIhvcNAQELBQADggIB
    AMkIrpfZSckITsEqRWxxvA6gd2HIqOJzMHnR+wVkMI0pRkX0As2IenRCtyAp4fRr
    zAFSi625RJUA+/QBtRKIOeZ1iaFBttw6qoG14ABecqygZY0lCT6iYdH6H2xp4C4b
    gcBMXhhRrTfMXsEyRtDefCFSpb2IGtflcA5gQuTo0OiNJ8+uHNTXcvZ6J9D7LG9T
    KpF1/KD4VehFHBuLzZLoPl4U5u8qPtsi+3lZ+CusdxmhISJ2zyqPsCB/jiSBqnQK
    sjem+Yv/znoLESVGzNqeTuekgIHVWfpruHhAszezEnSq6QtyKYQAKuGx3Q33KAC5
    gAgtbRnuCL+lAPoA0YQPtxwdhuXRjVFp0122wMiTT5A78Z4sdUd58pAsgfdu86Mp
    pdHDUUZMa4vmVanp4ADEe7tlS1U56O6vi+80C0tUVJ1BJivgRIyWOUEBU/K06fK6
    TRh1y7t+d24wbwu5RkFSPSnSX+oiCd5hL4odJRJ7LBzqC81y79EB+d0o2t2QBK6z
    rw1K831Un7jlZbDuB+M/iO1tdE/o8Uy0uzKE7v331gE8g8xPUnWW8QBqkYEMW8Yd
    7vLPo6XXL2JkO19C3xDAikZkv4akWGQDK7DHJMTa1fgylKK7E8zgovWIOqOG3gkj
    8KD/USuDE+Rtc5Pj+FSltBRzNz7b3F7jUrburZ+JctBx
    -----END CERTIFICATE----- 
  type: OpenStack
  openstack:
    externalNetwork: evpn-external
    computeAZs:
      - az1
      - az2
      - az3
    controlPlaneFlavor: ocp-controller-small
    workerFlavor: ocp-worker
