{{- range .Values.assignments -}}
{{- $nodeConfig := get $.Values.nodes .node -}}
{{- if not (eq .assignmentType "agent-nobmh") -}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
  name: {{ .node }}-creds
  namespace: {{ .namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: {{ .node }}-creds
    creationPolicy: Orphan
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        username: '{{ "{{ .username }}" }}'
        password: '{{ "{{ .password }}" }}'
  data:
  - secretKey: username
    remoteRef:
      key: {{ $nodeConfig.bmc.externalSecret.vaultName }}
      property: {{ $nodeConfig.bmc.externalSecret.usernameKey }}
  - secretKey: password
    remoteRef:
      key: {{ $nodeConfig.bmc.externalSecret.vaultName }}
      property: {{ $nodeConfig.bmc.externalSecret.passwordKey }}
---
{{ end }}
{{ end }}
